modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/chremastics/forge_updates.json?neoforge=only"
displayURL="https://modrinth.com/mod/chremastics"
logoFile="logo.png"
#credits=""

[[dependencies.${mod_id}]]
modId="vortylib"
type="required"
versionRange="[1.2.5,)"
ordering="NONE"
side="BOTH"

authors="Vortianski"

description='''
Terraria-inspired monetary system for Minecraft
'''

[[mixins]]
config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"